// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAlertService is an autogenerated mock type for the AlertService type
type MockAlertService struct {
	mock.Mock
}

type MockAlertService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlertService) EXPECT() *MockAlertService_Expecter {
	return &MockAlertService_Expecter{mock: &_m.Mock}
}

// Process provides a mock function with given fields: ctx, tracker, fetchErr, stats
func (_m *MockAlertService) Process(ctx context.Context, tracker *domain.Tracker, fetchErr error, stats *domain.TrackerStats) error {
	ret := _m.Called(ctx, tracker, fetchErr, stats)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Tracker, error, *domain.TrackerStats) error); ok {
		r0 = rf(ctx, tracker, fetchErr, stats)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertService_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockAlertService_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - tracker *domain.Tracker
//   - fetchErr error
//   - stats *domain.TrackerStats
func (_e *MockAlertService_Expecter) Process(ctx interface{}, tracker interface{}, fetchErr interface{}, stats interface{}) *MockAlertService_Process_Call {
	return &MockAlertService_Process_Call{Call: _e.mock.On("Process", ctx, tracker, fetchErr, stats)}
}

func (_c *MockAlertService_Process_Call) Run(run func(ctx context.Context, tracker *domain.Tracker, fetchErr error, stats *domain.TrackerStats)) *MockAlertService_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Tracker), args[2].(error), args[3].(*domain.TrackerStats))
	})
	return _c
}

func (_c *MockAlertService_Process_Call) Return(_a0 error) *MockAlertService_Process_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertService_Process_Call) RunAndReturn(run func(context.Context, *domain.Tracker, error, *domain.TrackerStats) error) *MockAlertService_Process_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlertService creates a new instance of MockAlertService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlertService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlertService {
	mock := &MockAlertService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
