// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAlertConfigService is an autogenerated mock type for the AlertConfigService type
type MockAlertConfigService struct {
	mock.Mock
}

type MockAlertConfigService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlertConfigService) EXPECT() *MockAlertConfigService_Expecter {
	return &MockAlertConfigService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: input
func (_m *MockAlertConfigService) Create(input domain.CreateAlertConfigInput) (*domain.AlertConfig, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.AlertConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.CreateAlertConfigInput) (*domain.AlertConfig, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(domain.CreateAlertConfigInput) *domain.AlertConfig); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AlertConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.CreateAlertConfigInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertConfigService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAlertConfigService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - input domain.CreateAlertConfigInput
func (_e *MockAlertConfigService_Expecter) Create(input interface{}) *MockAlertConfigService_Create_Call {
	return &MockAlertConfigService_Create_Call{Call: _e.mock.On("Create", input)}
}

func (_c *MockAlertConfigService_Create_Call) Run(run func(input domain.CreateAlertConfigInput)) *MockAlertConfigService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.CreateAlertConfigInput))
	})
	return _c
}

func (_c *MockAlertConfigService_Create_Call) Return(_a0 *domain.AlertConfig, _a1 error) *MockAlertConfigService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertConfigService_Create_Call) RunAndReturn(run func(domain.CreateAlertConfigInput) (*domain.AlertConfig, error)) *MockAlertConfigService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockAlertConfigService) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertConfigService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAlertConfigService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockAlertConfigService_Expecter) Delete(id interface{}) *MockAlertConfigService_Delete_Call {
	return &MockAlertConfigService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockAlertConfigService_Delete_Call) Run(run func(id uint)) *MockAlertConfigService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockAlertConfigService_Delete_Call) Return(_a0 error) *MockAlertConfigService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertConfigService_Delete_Call) RunAndReturn(run func(uint) error) *MockAlertConfigService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockAlertConfigService) GetAll() ([]domain.AlertConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.AlertConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.AlertConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.AlertConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AlertConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertConfigService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockAlertConfigService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockAlertConfigService_Expecter) GetAll() *MockAlertConfigService_GetAll_Call {
	return &MockAlertConfigService_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockAlertConfigService_GetAll_Call) Run(run func()) *MockAlertConfigService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAlertConfigService_GetAll_Call) Return(_a0 []domain.AlertConfig, _a1 error) *MockAlertConfigService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertConfigService_GetAll_Call) RunAndReturn(run func() ([]domain.AlertConfig, error)) *MockAlertConfigService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockAlertConfigService) GetByID(id uint) (*domain.AlertConfig, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.AlertConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.AlertConfig, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.AlertConfig); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AlertConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertConfigService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAlertConfigService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockAlertConfigService_Expecter) GetByID(id interface{}) *MockAlertConfigService_GetByID_Call {
	return &MockAlertConfigService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockAlertConfigService_GetByID_Call) Run(run func(id uint)) *MockAlertConfigService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockAlertConfigService_GetByID_Call) Return(_a0 *domain.AlertConfig, _a1 error) *MockAlertConfigService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertConfigService_GetByID_Call) RunAndReturn(run func(uint) (*domain.AlertConfig, error)) *MockAlertConfigService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, input
func (_m *MockAlertConfigService) Update(id uint, input domain.UpdateAlertConfigInput) (*domain.AlertConfig, error) {
	ret := _m.Called(id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.AlertConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, domain.UpdateAlertConfigInput) (*domain.AlertConfig, error)); ok {
		return rf(id, input)
	}
	if rf, ok := ret.Get(0).(func(uint, domain.UpdateAlertConfigInput) *domain.AlertConfig); ok {
		r0 = rf(id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AlertConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, domain.UpdateAlertConfigInput) error); ok {
		r1 = rf(id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertConfigService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAlertConfigService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uint
//   - input domain.UpdateAlertConfigInput
func (_e *MockAlertConfigService_Expecter) Update(id interface{}, input interface{}) *MockAlertConfigService_Update_Call {
	return &MockAlertConfigService_Update_Call{Call: _e.mock.On("Update", id, input)}
}

func (_c *MockAlertConfigService_Update_Call) Run(run func(id uint, input domain.UpdateAlertConfigInput)) *MockAlertConfigService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(domain.UpdateAlertConfigInput))
	})
	return _c
}

func (_c *MockAlertConfigService_Update_Call) Return(_a0 *domain.AlertConfig, _a1 error) *MockAlertConfigService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertConfigService_Update_Call) RunAndReturn(run func(uint, domain.UpdateAlertConfigInput) (*domain.AlertConfig, error)) *MockAlertConfigService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlertConfigService creates a new instance of MockAlertConfigService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlertConfigService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlertConfigService {
	mock := &MockAlertConfigService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
