// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockReportScheduler is an autogenerated mock type for the ReportScheduler type
type MockReportScheduler struct {
	mock.Mock
}

type MockReportScheduler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportScheduler) EXPECT() *MockReportScheduler_Expecter {
	return &MockReportScheduler_Expecter{mock: &_m.Mock}
}

// ScheduleReport provides a mock function with given fields: report
func (_m *MockReportScheduler) ScheduleReport(report domain.Report) error {
	ret := _m.Called(report)
	if len(ret) == 0 {
		panic("no return value specified for ScheduleReport")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Report) error); ok {
		r0 = rf(report)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type MockReportScheduler_ScheduleReport_Call struct{ *mock.Call }

func (_e *MockReportScheduler_Expecter) ScheduleReport(report interface{}) *MockReportScheduler_ScheduleReport_Call {
	return &MockReportScheduler_ScheduleReport_Call{Call: _e.mock.On("ScheduleReport", report)}
}

func (_c *MockReportScheduler_ScheduleReport_Call) Run(run func(report domain.Report)) *MockReportScheduler_ScheduleReport_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(domain.Report)) })
	return _c
}

func (_c *MockReportScheduler_ScheduleReport_Call) Return(_a0 error) *MockReportScheduler_ScheduleReport_Call {
	_c.Call.Return(_a0)
	return _c
}

// UnscheduleReport provides a mock function with given fields: reportID
func (_m *MockReportScheduler) UnscheduleReport(reportID uint) {
	_m.Called(reportID)
}

type MockReportScheduler_UnscheduleReport_Call struct{ *mock.Call }

func (_e *MockReportScheduler_Expecter) UnscheduleReport(reportID interface{}) *MockReportScheduler_UnscheduleReport_Call {
	return &MockReportScheduler_UnscheduleReport_Call{Call: _e.mock.On("UnscheduleReport", reportID)}
}

func (_c *MockReportScheduler_UnscheduleReport_Call) Run(run func(reportID uint)) *MockReportScheduler_UnscheduleReport_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(uint)) })
	return _c
}

func (_c *MockReportScheduler_UnscheduleReport_Call) Return() *MockReportScheduler_UnscheduleReport_Call {
	_c.Call.Return()
	return _c
}

// NewMockReportScheduler creates a new instance of MockReportScheduler.
func NewMockReportScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportScheduler {
	mock := &MockReportScheduler{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
