// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockScraperRegistry is an autogenerated mock type for the ScraperRegistry type
type MockScraperRegistry struct {
	mock.Mock
}

type MockScraperRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScraperRegistry) EXPECT() *MockScraperRegistry_Expecter {
	return &MockScraperRegistry_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *MockScraperRegistry) Get(key string) (domain.TrackerScraper, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.TrackerScraper
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (domain.TrackerScraper, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) domain.TrackerScraper); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.TrackerScraper)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockScraperRegistry_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockScraperRegistry_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockScraperRegistry_Expecter) Get(key interface{}) *MockScraperRegistry_Get_Call {
	return &MockScraperRegistry_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockScraperRegistry_Get_Call) Run(run func(key string)) *MockScraperRegistry_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockScraperRegistry_Get_Call) Return(_a0 domain.TrackerScraper, _a1 bool) *MockScraperRegistry_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScraperRegistry_Get_Call) RunAndReturn(run func(string) (domain.TrackerScraper, bool)) *MockScraperRegistry_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Keys provides a mock function with no fields
func (_m *MockScraperRegistry) Keys() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockScraperRegistry_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type MockScraperRegistry_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
func (_e *MockScraperRegistry_Expecter) Keys() *MockScraperRegistry_Keys_Call {
	return &MockScraperRegistry_Keys_Call{Call: _e.mock.On("Keys")}
}

func (_c *MockScraperRegistry_Keys_Call) Run(run func()) *MockScraperRegistry_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScraperRegistry_Keys_Call) Return(_a0 []string) *MockScraperRegistry_Keys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScraperRegistry_Keys_Call) RunAndReturn(run func() []string) *MockScraperRegistry_Keys_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScraperRegistry creates a new instance of MockScraperRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScraperRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScraperRegistry {
	mock := &MockScraperRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
