// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockStatsRepository is an autogenerated mock type for the StatsRepository type
type MockStatsRepository struct {
	mock.Mock
}

type MockStatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatsRepository) EXPECT() *MockStatsRepository_Expecter {
	return &MockStatsRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: stats
func (_m *MockStatsRepository) Create(stats *domain.TrackerStats) error {
	ret := _m.Called(stats)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.TrackerStats) error); ok {
		r0 = rf(stats)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStatsRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStatsRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - stats *domain.TrackerStats
func (_e *MockStatsRepository_Expecter) Create(stats interface{}) *MockStatsRepository_Create_Call {
	return &MockStatsRepository_Create_Call{Call: _e.mock.On("Create", stats)}
}

func (_c *MockStatsRepository_Create_Call) Run(run func(stats *domain.TrackerStats)) *MockStatsRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.TrackerStats))
	})
	return _c
}

func (_c *MockStatsRepository_Create_Call) Return(_a0 error) *MockStatsRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStatsRepository_Create_Call) RunAndReturn(run func(*domain.TrackerStats) error) *MockStatsRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: statID, trackerID
func (_m *MockStatsRepository) Delete(statID uint, trackerID uint) error {
	ret := _m.Called(statID, trackerID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(statID, trackerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStatsRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStatsRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - statID uint
//   - trackerID uint
func (_e *MockStatsRepository_Expecter) Delete(statID interface{}, trackerID interface{}) *MockStatsRepository_Delete_Call {
	return &MockStatsRepository_Delete_Call{Call: _e.mock.On("Delete", statID, trackerID)}
}

func (_c *MockStatsRepository_Delete_Call) Run(run func(statID uint, trackerID uint)) *MockStatsRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint))
	})
	return _c
}

func (_c *MockStatsRepository_Delete_Call) Return(_a0 error) *MockStatsRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStatsRepository_Delete_Call) RunAndReturn(run func(uint, uint) error) *MockStatsRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTrackerID provides a mock function with given fields: trackerID, limit
func (_m *MockStatsRepository) FindByTrackerID(trackerID uint, limit int) ([]domain.TrackerStats, error) {
	ret := _m.Called(trackerID, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByTrackerID")
	}

	var r0 []domain.TrackerStats
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, int) ([]domain.TrackerStats, error)); ok {
		return rf(trackerID, limit)
	}
	if rf, ok := ret.Get(0).(func(uint, int) []domain.TrackerStats); ok {
		r0 = rf(trackerID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TrackerStats)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int) error); ok {
		r1 = rf(trackerID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsRepository_FindByTrackerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTrackerID'
type MockStatsRepository_FindByTrackerID_Call struct {
	*mock.Call
}

// FindByTrackerID is a helper method to define mock.On call
//   - trackerID uint
//   - limit int
func (_e *MockStatsRepository_Expecter) FindByTrackerID(trackerID interface{}, limit interface{}) *MockStatsRepository_FindByTrackerID_Call {
	return &MockStatsRepository_FindByTrackerID_Call{Call: _e.mock.On("FindByTrackerID", trackerID, limit)}
}

func (_c *MockStatsRepository_FindByTrackerID_Call) Run(run func(trackerID uint, limit int)) *MockStatsRepository_FindByTrackerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(int))
	})
	return _c
}

func (_c *MockStatsRepository_FindByTrackerID_Call) Return(_a0 []domain.TrackerStats, _a1 error) *MockStatsRepository_FindByTrackerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsRepository_FindByTrackerID_Call) RunAndReturn(run func(uint, int) ([]domain.TrackerStats, error)) *MockStatsRepository_FindByTrackerID_Call {
	_c.Call.Return(run)
	return _c
}

// FindGlobalHistory provides a mock function with given fields: since
func (_m *MockStatsRepository) FindGlobalHistory(since time.Time) ([]domain.GlobalStatsPoint, error) {
	ret := _m.Called(since)

	if len(ret) == 0 {
		panic("no return value specified for FindGlobalHistory")
	}

	var r0 []domain.GlobalStatsPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time) ([]domain.GlobalStatsPoint, error)); ok {
		return rf(since)
	}
	if rf, ok := ret.Get(0).(func(time.Time) []domain.GlobalStatsPoint); ok {
		r0 = rf(since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.GlobalStatsPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsRepository_FindGlobalHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindGlobalHistory'
type MockStatsRepository_FindGlobalHistory_Call struct {
	*mock.Call
}

// FindGlobalHistory is a helper method to define mock.On call
//   - since time.Time
func (_e *MockStatsRepository_Expecter) FindGlobalHistory(since interface{}) *MockStatsRepository_FindGlobalHistory_Call {
	return &MockStatsRepository_FindGlobalHistory_Call{Call: _e.mock.On("FindGlobalHistory", since)}
}

func (_c *MockStatsRepository_FindGlobalHistory_Call) Run(run func(since time.Time)) *MockStatsRepository_FindGlobalHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *MockStatsRepository_FindGlobalHistory_Call) Return(_a0 []domain.GlobalStatsPoint, _a1 error) *MockStatsRepository_FindGlobalHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsRepository_FindGlobalHistory_Call) RunAndReturn(run func(time.Time) ([]domain.GlobalStatsPoint, error)) *MockStatsRepository_FindGlobalHistory_Call {
	_c.Call.Return(run)
	return _c
}

// FindLatestAll provides a mock function with no fields
func (_m *MockStatsRepository) FindLatestAll() ([]domain.TrackerStats, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindLatestAll")
	}

	var r0 []domain.TrackerStats
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.TrackerStats, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.TrackerStats); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TrackerStats)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsRepository_FindLatestAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLatestAll'
type MockStatsRepository_FindLatestAll_Call struct {
	*mock.Call
}

// FindLatestAll is a helper method to define mock.On call
func (_e *MockStatsRepository_Expecter) FindLatestAll() *MockStatsRepository_FindLatestAll_Call {
	return &MockStatsRepository_FindLatestAll_Call{Call: _e.mock.On("FindLatestAll")}
}

func (_c *MockStatsRepository_FindLatestAll_Call) Run(run func()) *MockStatsRepository_FindLatestAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStatsRepository_FindLatestAll_Call) Return(_a0 []domain.TrackerStats, _a1 error) *MockStatsRepository_FindLatestAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsRepository_FindLatestAll_Call) RunAndReturn(run func() ([]domain.TrackerStats, error)) *MockStatsRepository_FindLatestAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindLatestByTrackerID provides a mock function with given fields: trackerID
func (_m *MockStatsRepository) FindLatestByTrackerID(trackerID uint) (*domain.TrackerStats, error) {
	ret := _m.Called(trackerID)

	if len(ret) == 0 {
		panic("no return value specified for FindLatestByTrackerID")
	}

	var r0 *domain.TrackerStats
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.TrackerStats, error)); ok {
		return rf(trackerID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.TrackerStats); ok {
		r0 = rf(trackerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TrackerStats)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(trackerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsRepository_FindLatestByTrackerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLatestByTrackerID'
type MockStatsRepository_FindLatestByTrackerID_Call struct {
	*mock.Call
}

// FindLatestByTrackerID is a helper method to define mock.On call
//   - trackerID uint
func (_e *MockStatsRepository_Expecter) FindLatestByTrackerID(trackerID interface{}) *MockStatsRepository_FindLatestByTrackerID_Call {
	return &MockStatsRepository_FindLatestByTrackerID_Call{Call: _e.mock.On("FindLatestByTrackerID", trackerID)}
}

func (_c *MockStatsRepository_FindLatestByTrackerID_Call) Run(run func(trackerID uint)) *MockStatsRepository_FindLatestByTrackerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockStatsRepository_FindLatestByTrackerID_Call) Return(_a0 *domain.TrackerStats, _a1 error) *MockStatsRepository_FindLatestByTrackerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsRepository_FindLatestByTrackerID_Call) RunAndReturn(run func(uint) (*domain.TrackerStats, error)) *MockStatsRepository_FindLatestByTrackerID_Call {
	_c.Call.Return(run)
	return _c
}

// FindNearestAtOrBefore provides a mock function with given fields: trackerID, t
func (_m *MockStatsRepository) FindNearestAtOrBefore(trackerID uint, t time.Time) (*domain.TrackerStats, error) {
	ret := _m.Called(trackerID, t)

	if len(ret) == 0 {
		panic("no return value specified for FindNearestAtOrBefore")
	}

	var r0 *domain.TrackerStats
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, time.Time) (*domain.TrackerStats, error)); ok {
		return rf(trackerID, t)
	}
	if rf, ok := ret.Get(0).(func(uint, time.Time) *domain.TrackerStats); ok {
		r0 = rf(trackerID, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TrackerStats)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, time.Time) error); ok {
		r1 = rf(trackerID, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsRepository_FindNearestAtOrBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNearestAtOrBefore'
type MockStatsRepository_FindNearestAtOrBefore_Call struct {
	*mock.Call
}

// FindNearestAtOrBefore is a helper method to define mock.On call
//   - trackerID uint
//   - t time.Time
func (_e *MockStatsRepository_Expecter) FindNearestAtOrBefore(trackerID interface{}, t interface{}) *MockStatsRepository_FindNearestAtOrBefore_Call {
	return &MockStatsRepository_FindNearestAtOrBefore_Call{Call: _e.mock.On("FindNearestAtOrBefore", trackerID, t)}
}

func (_c *MockStatsRepository_FindNearestAtOrBefore_Call) Run(run func(trackerID uint, t time.Time)) *MockStatsRepository_FindNearestAtOrBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(time.Time))
	})
	return _c
}

func (_c *MockStatsRepository_FindNearestAtOrBefore_Call) Return(_a0 *domain.TrackerStats, _a1 error) *MockStatsRepository_FindNearestAtOrBefore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsRepository_FindNearestAtOrBefore_Call) RunAndReturn(run func(uint, time.Time) (*domain.TrackerStats, error)) *MockStatsRepository_FindNearestAtOrBefore_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTrackerIDSince provides a mock function with given fields: trackerID, since
func (_m *MockStatsRepository) FindByTrackerIDSince(trackerID uint, since time.Time) ([]domain.TrackerStats, error) {
	ret := _m.Called(trackerID, since)

	if len(ret) == 0 {
		panic("no return value specified for FindByTrackerIDSince")
	}

	var r0 []domain.TrackerStats
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, time.Time) ([]domain.TrackerStats, error)); ok {
		return rf(trackerID, since)
	}
	if rf, ok := ret.Get(0).(func(uint, time.Time) []domain.TrackerStats); ok {
		r0 = rf(trackerID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TrackerStats)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, time.Time) error); ok {
		r1 = rf(trackerID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsRepository_FindByTrackerIDSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTrackerIDSince'
type MockStatsRepository_FindByTrackerIDSince_Call struct {
	*mock.Call
}

// FindByTrackerIDSince is a helper method to define mock.On call
//   - trackerID uint
//   - since time.Time
func (_e *MockStatsRepository_Expecter) FindByTrackerIDSince(trackerID interface{}, since interface{}) *MockStatsRepository_FindByTrackerIDSince_Call {
	return &MockStatsRepository_FindByTrackerIDSince_Call{Call: _e.mock.On("FindByTrackerIDSince", trackerID, since)}
}

func (_c *MockStatsRepository_FindByTrackerIDSince_Call) Run(run func(trackerID uint, since time.Time)) *MockStatsRepository_FindByTrackerIDSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(time.Time))
	})
	return _c
}

func (_c *MockStatsRepository_FindByTrackerIDSince_Call) Return(_a0 []domain.TrackerStats, _a1 error) *MockStatsRepository_FindByTrackerIDSince_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsRepository_FindByTrackerIDSince_Call) RunAndReturn(run func(uint, time.Time) ([]domain.TrackerStats, error)) *MockStatsRepository_FindByTrackerIDSince_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatsRepository creates a new instance of MockStatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatsRepository {
	mock := &MockStatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
