// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockReportService is an autogenerated mock type for the ReportService type
type MockReportService struct {
	mock.Mock
}

type MockReportService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportService) EXPECT() *MockReportService_Expecter {
	return &MockReportService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: input
func (_m *MockReportService) Create(input domain.CreateReportInput) (*domain.Report, error) {
	ret := _m.Called(input)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 *domain.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.CreateReportInput) (*domain.Report, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(domain.CreateReportInput) *domain.Report); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Report)
		}
	}
	if rf, ok := ret.Get(1).(func(domain.CreateReportInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockReportService_Create_Call struct{ *mock.Call }

func (_e *MockReportService_Expecter) Create(input interface{}) *MockReportService_Create_Call {
	return &MockReportService_Create_Call{Call: _e.mock.On("Create", input)}
}

func (_c *MockReportService_Create_Call) Run(run func(input domain.CreateReportInput)) *MockReportService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(domain.CreateReportInput)) })
	return _c
}

func (_c *MockReportService_Create_Call) Return(_a0 *domain.Report, _a1 error) *MockReportService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockReportService) Delete(id uint) error {
	ret := _m.Called(id)
	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type MockReportService_Delete_Call struct{ *mock.Call }

func (_e *MockReportService_Expecter) Delete(id interface{}) *MockReportService_Delete_Call {
	return &MockReportService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockReportService_Delete_Call) Run(run func(id uint)) *MockReportService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(uint)) })
	return _c
}

func (_c *MockReportService_Delete_Call) Return(_a0 error) *MockReportService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockReportService) GetAll() ([]domain.Report, error) {
	ret := _m.Called()
	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}
	var r0 []domain.Report
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Report, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Report); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Report)
		}
	}
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockReportService_GetAll_Call struct{ *mock.Call }

func (_e *MockReportService_Expecter) GetAll() *MockReportService_GetAll_Call {
	return &MockReportService_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockReportService_GetAll_Call) Run(run func()) *MockReportService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) { run() })
	return _c
}

func (_c *MockReportService_GetAll_Call) Return(_a0 []domain.Report, _a1 error) *MockReportService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockReportService) GetByID(id uint) (*domain.Report, error) {
	ret := _m.Called(id)
	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}
	var r0 *domain.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Report, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Report); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Report)
		}
	}
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockReportService_GetByID_Call struct{ *mock.Call }

func (_e *MockReportService_Expecter) GetByID(id interface{}) *MockReportService_GetByID_Call {
	return &MockReportService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockReportService_GetByID_Call) Run(run func(id uint)) *MockReportService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(uint)) })
	return _c
}

func (_c *MockReportService_GetByID_Call) Return(_a0 *domain.Report, _a1 error) *MockReportService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Send provides a mock function with given fields: ctx, id
func (_m *MockReportService) Send(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)
	if len(ret) == 0 {
		panic("no return value specified for Send")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type MockReportService_Send_Call struct{ *mock.Call }

func (_e *MockReportService_Expecter) Send(ctx interface{}, id interface{}) *MockReportService_Send_Call {
	return &MockReportService_Send_Call{Call: _e.mock.On("Send", ctx, id)}
}

func (_c *MockReportService_Send_Call) Run(run func(ctx context.Context, id uint)) *MockReportService_Send_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(context.Context), args[1].(uint)) })
	return _c
}

func (_c *MockReportService_Send_Call) Return(_a0 error) *MockReportService_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

// Update provides a mock function with given fields: id, input
func (_m *MockReportService) Update(id uint, input domain.UpdateReportInput) (*domain.Report, error) {
	ret := _m.Called(id, input)
	if len(ret) == 0 {
		panic("no return value specified for Update")
	}
	var r0 *domain.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, domain.UpdateReportInput) (*domain.Report, error)); ok {
		return rf(id, input)
	}
	if rf, ok := ret.Get(0).(func(uint, domain.UpdateReportInput) *domain.Report); ok {
		r0 = rf(id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Report)
		}
	}
	if rf, ok := ret.Get(1).(func(uint, domain.UpdateReportInput) error); ok {
		r1 = rf(id, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockReportService_Update_Call struct{ *mock.Call }

func (_e *MockReportService_Expecter) Update(id interface{}, input interface{}) *MockReportService_Update_Call {
	return &MockReportService_Update_Call{Call: _e.mock.On("Update", id, input)}
}

func (_c *MockReportService_Update_Call) Run(run func(id uint, input domain.UpdateReportInput)) *MockReportService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(uint), args[1].(domain.UpdateReportInput)) })
	return _c
}

func (_c *MockReportService_Update_Call) Return(_a0 *domain.Report, _a1 error) *MockReportService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// NewMockReportService creates a new instance of MockReportService.
func NewMockReportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportService {
	mock := &MockReportService{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
