// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTrackerRepository is an autogenerated mock type for the TrackerRepository type
type MockTrackerRepository struct {
	mock.Mock
}

type MockTrackerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrackerRepository) EXPECT() *MockTrackerRepository_Expecter {
	return &MockTrackerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: tracker
func (_m *MockTrackerRepository) Create(tracker *domain.Tracker) error {
	ret := _m.Called(tracker)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Tracker) error); ok {
		r0 = rf(tracker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTrackerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTrackerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tracker *domain.Tracker
func (_e *MockTrackerRepository_Expecter) Create(tracker interface{}) *MockTrackerRepository_Create_Call {
	return &MockTrackerRepository_Create_Call{Call: _e.mock.On("Create", tracker)}
}

func (_c *MockTrackerRepository_Create_Call) Run(run func(tracker *domain.Tracker)) *MockTrackerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Tracker))
	})
	return _c
}

func (_c *MockTrackerRepository_Create_Call) Return(_a0 error) *MockTrackerRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackerRepository_Create_Call) RunAndReturn(run func(*domain.Tracker) error) *MockTrackerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockTrackerRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTrackerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTrackerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockTrackerRepository_Expecter) Delete(id interface{}) *MockTrackerRepository_Delete_Call {
	return &MockTrackerRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockTrackerRepository_Delete_Call) Run(run func(id uint)) *MockTrackerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockTrackerRepository_Delete_Call) Return(_a0 error) *MockTrackerRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackerRepository_Delete_Call) RunAndReturn(run func(uint) error) *MockTrackerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindActive provides a mock function with no fields
func (_m *MockTrackerRepository) FindActive() ([]domain.Tracker, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindActive")
	}

	var r0 []domain.Tracker
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Tracker, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Tracker); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tracker)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTrackerRepository_FindActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActive'
type MockTrackerRepository_FindActive_Call struct {
	*mock.Call
}

// FindActive is a helper method to define mock.On call
func (_e *MockTrackerRepository_Expecter) FindActive() *MockTrackerRepository_FindActive_Call {
	return &MockTrackerRepository_FindActive_Call{Call: _e.mock.On("FindActive")}
}

func (_c *MockTrackerRepository_FindActive_Call) Run(run func()) *MockTrackerRepository_FindActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrackerRepository_FindActive_Call) Return(_a0 []domain.Tracker, _a1 error) *MockTrackerRepository_FindActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackerRepository_FindActive_Call) RunAndReturn(run func() ([]domain.Tracker, error)) *MockTrackerRepository_FindActive_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with no fields
func (_m *MockTrackerRepository) FindAll() ([]domain.Tracker, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Tracker
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Tracker, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Tracker); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tracker)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTrackerRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockTrackerRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockTrackerRepository_Expecter) FindAll() *MockTrackerRepository_FindAll_Call {
	return &MockTrackerRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockTrackerRepository_FindAll_Call) Run(run func()) *MockTrackerRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrackerRepository_FindAll_Call) Return(_a0 []domain.Tracker, _a1 error) *MockTrackerRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackerRepository_FindAll_Call) RunAndReturn(run func() ([]domain.Tracker, error)) *MockTrackerRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockTrackerRepository) FindByID(id uint) (*domain.Tracker, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Tracker
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Tracker, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Tracker); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tracker)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTrackerRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTrackerRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint
func (_e *MockTrackerRepository_Expecter) FindByID(id interface{}) *MockTrackerRepository_FindByID_Call {
	return &MockTrackerRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockTrackerRepository_FindByID_Call) Run(run func(id uint)) *MockTrackerRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockTrackerRepository_FindByID_Call) Return(_a0 *domain.Tracker, _a1 error) *MockTrackerRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackerRepository_FindByID_Call) RunAndReturn(run func(uint) (*domain.Tracker, error)) *MockTrackerRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: tracker
func (_m *MockTrackerRepository) Update(tracker *domain.Tracker) error {
	ret := _m.Called(tracker)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Tracker) error); ok {
		r0 = rf(tracker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTrackerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTrackerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tracker *domain.Tracker
func (_e *MockTrackerRepository_Expecter) Update(tracker interface{}) *MockTrackerRepository_Update_Call {
	return &MockTrackerRepository_Update_Call{Call: _e.mock.On("Update", tracker)}
}

func (_c *MockTrackerRepository_Update_Call) Run(run func(tracker *domain.Tracker)) *MockTrackerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Tracker))
	})
	return _c
}

func (_c *MockTrackerRepository_Update_Call) Return(_a0 error) *MockTrackerRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackerRepository_Update_Call) RunAndReturn(run func(*domain.Tracker) error) *MockTrackerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateScrapeStatus provides a mock function with given fields: trackerID, lastError
func (_m *MockTrackerRepository) UpdateScrapeStatus(trackerID uint, lastError string) error {
	ret := _m.Called(trackerID, lastError)

	if len(ret) == 0 {
		panic("no return value specified for UpdateScrapeStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = rf(trackerID, lastError)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTrackerRepository_UpdateScrapeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateScrapeStatus'
type MockTrackerRepository_UpdateScrapeStatus_Call struct {
	*mock.Call
}

// UpdateScrapeStatus is a helper method to define mock.On call
//   - trackerID uint
//   - lastError string
func (_e *MockTrackerRepository_Expecter) UpdateScrapeStatus(trackerID interface{}, lastError interface{}) *MockTrackerRepository_UpdateScrapeStatus_Call {
	return &MockTrackerRepository_UpdateScrapeStatus_Call{Call: _e.mock.On("UpdateScrapeStatus", trackerID, lastError)}
}

func (_c *MockTrackerRepository_UpdateScrapeStatus_Call) Run(run func(trackerID uint, lastError string)) *MockTrackerRepository_UpdateScrapeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(string))
	})
	return _c
}

func (_c *MockTrackerRepository_UpdateScrapeStatus_Call) Return(_a0 error) *MockTrackerRepository_UpdateScrapeStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackerRepository_UpdateScrapeStatus_Call) RunAndReturn(run func(uint, string) error) *MockTrackerRepository_UpdateScrapeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTrackerRepository creates a new instance of MockTrackerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrackerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrackerRepository {
	mock := &MockTrackerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
