// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockNotifierConfigService is an autogenerated mock type for the NotifierConfigService type
type MockNotifierConfigService struct {
	mock.Mock
}

type MockNotifierConfigService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifierConfigService) EXPECT() *MockNotifierConfigService_Expecter {
	return &MockNotifierConfigService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: input
func (_m *MockNotifierConfigService) Create(input domain.CreateNotifierConfigInput) (*domain.NotifierConfig, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.NotifierConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.CreateNotifierConfigInput) (*domain.NotifierConfig, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(domain.CreateNotifierConfigInput) *domain.NotifierConfig); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.NotifierConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.CreateNotifierConfigInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotifierConfigService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNotifierConfigService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - input domain.CreateNotifierConfigInput
func (_e *MockNotifierConfigService_Expecter) Create(input interface{}) *MockNotifierConfigService_Create_Call {
	return &MockNotifierConfigService_Create_Call{Call: _e.mock.On("Create", input)}
}

func (_c *MockNotifierConfigService_Create_Call) Run(run func(input domain.CreateNotifierConfigInput)) *MockNotifierConfigService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.CreateNotifierConfigInput))
	})
	return _c
}

func (_c *MockNotifierConfigService_Create_Call) Return(_a0 *domain.NotifierConfig, _a1 error) *MockNotifierConfigService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotifierConfigService_Create_Call) RunAndReturn(run func(domain.CreateNotifierConfigInput) (*domain.NotifierConfig, error)) *MockNotifierConfigService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockNotifierConfigService) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifierConfigService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNotifierConfigService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockNotifierConfigService_Expecter) Delete(id interface{}) *MockNotifierConfigService_Delete_Call {
	return &MockNotifierConfigService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockNotifierConfigService_Delete_Call) Run(run func(id uint)) *MockNotifierConfigService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockNotifierConfigService_Delete_Call) Return(_a0 error) *MockNotifierConfigService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifierConfigService_Delete_Call) RunAndReturn(run func(uint) error) *MockNotifierConfigService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockNotifierConfigService) GetAll() ([]domain.NotifierConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.NotifierConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.NotifierConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.NotifierConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.NotifierConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotifierConfigService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockNotifierConfigService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockNotifierConfigService_Expecter) GetAll() *MockNotifierConfigService_GetAll_Call {
	return &MockNotifierConfigService_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockNotifierConfigService_GetAll_Call) Run(run func()) *MockNotifierConfigService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifierConfigService_GetAll_Call) Return(_a0 []domain.NotifierConfig, _a1 error) *MockNotifierConfigService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotifierConfigService_GetAll_Call) RunAndReturn(run func() ([]domain.NotifierConfig, error)) *MockNotifierConfigService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockNotifierConfigService) GetByID(id uint) (*domain.NotifierConfig, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.NotifierConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.NotifierConfig, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.NotifierConfig); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.NotifierConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotifierConfigService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockNotifierConfigService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockNotifierConfigService_Expecter) GetByID(id interface{}) *MockNotifierConfigService_GetByID_Call {
	return &MockNotifierConfigService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockNotifierConfigService_GetByID_Call) Run(run func(id uint)) *MockNotifierConfigService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockNotifierConfigService_GetByID_Call) Return(_a0 *domain.NotifierConfig, _a1 error) *MockNotifierConfigService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotifierConfigService_GetByID_Call) RunAndReturn(run func(uint) (*domain.NotifierConfig, error)) *MockNotifierConfigService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnabled provides a mock function with no fields
func (_m *MockNotifierConfigService) GetEnabled() ([]domain.NotifierConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEnabled")
	}

	var r0 []domain.NotifierConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.NotifierConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.NotifierConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.NotifierConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotifierConfigService_GetEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnabled'
type MockNotifierConfigService_GetEnabled_Call struct {
	*mock.Call
}

// GetEnabled is a helper method to define mock.On call
func (_e *MockNotifierConfigService_Expecter) GetEnabled() *MockNotifierConfigService_GetEnabled_Call {
	return &MockNotifierConfigService_GetEnabled_Call{Call: _e.mock.On("GetEnabled")}
}

func (_c *MockNotifierConfigService_GetEnabled_Call) Run(run func()) *MockNotifierConfigService_GetEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifierConfigService_GetEnabled_Call) Return(_a0 []domain.NotifierConfig, _a1 error) *MockNotifierConfigService_GetEnabled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotifierConfigService_GetEnabled_Call) RunAndReturn(run func() ([]domain.NotifierConfig, error)) *MockNotifierConfigService_GetEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// Test provides a mock function with given fields: cfgType, cfgJSON
func (_m *MockNotifierConfigService) Test(cfgType string, cfgJSON string) error {
	ret := _m.Called(cfgType, cfgJSON)

	if len(ret) == 0 {
		panic("no return value specified for Test")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(cfgType, cfgJSON)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifierConfigService_Test_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Test'
type MockNotifierConfigService_Test_Call struct {
	*mock.Call
}

// Test is a helper method to define mock.On call
//   - cfgType string
//   - cfgJSON string
func (_e *MockNotifierConfigService_Expecter) Test(cfgType interface{}, cfgJSON interface{}) *MockNotifierConfigService_Test_Call {
	return &MockNotifierConfigService_Test_Call{Call: _e.mock.On("Test", cfgType, cfgJSON)}
}

func (_c *MockNotifierConfigService_Test_Call) Run(run func(cfgType string, cfgJSON string)) *MockNotifierConfigService_Test_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockNotifierConfigService_Test_Call) Return(_a0 error) *MockNotifierConfigService_Test_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifierConfigService_Test_Call) RunAndReturn(run func(string, string) error) *MockNotifierConfigService_Test_Call {
	_c.Call.Return(run)
	return _c
}

// TestByID provides a mock function with given fields: id, configOverride
func (_m *MockNotifierConfigService) TestByID(id uint, configOverride string) error {
	ret := _m.Called(id, configOverride)

	if len(ret) == 0 {
		panic("no return value specified for TestByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = rf(id, configOverride)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifierConfigService_TestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestByID'
type MockNotifierConfigService_TestByID_Call struct {
	*mock.Call
}

// TestByID is a helper method to define mock.On call
//   - id uint
//   - configOverride string
func (_e *MockNotifierConfigService_Expecter) TestByID(id interface{}, configOverride interface{}) *MockNotifierConfigService_TestByID_Call {
	return &MockNotifierConfigService_TestByID_Call{Call: _e.mock.On("TestByID", id, configOverride)}
}

func (_c *MockNotifierConfigService_TestByID_Call) Run(run func(id uint, configOverride string)) *MockNotifierConfigService_TestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(string))
	})
	return _c
}

func (_c *MockNotifierConfigService_TestByID_Call) Return(_a0 error) *MockNotifierConfigService_TestByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifierConfigService_TestByID_Call) RunAndReturn(run func(uint, string) error) *MockNotifierConfigService_TestByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, input
func (_m *MockNotifierConfigService) Update(id uint, input domain.UpdateNotifierConfigInput) (*domain.NotifierConfig, error) {
	ret := _m.Called(id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.NotifierConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, domain.UpdateNotifierConfigInput) (*domain.NotifierConfig, error)); ok {
		return rf(id, input)
	}
	if rf, ok := ret.Get(0).(func(uint, domain.UpdateNotifierConfigInput) *domain.NotifierConfig); ok {
		r0 = rf(id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.NotifierConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, domain.UpdateNotifierConfigInput) error); ok {
		r1 = rf(id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotifierConfigService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockNotifierConfigService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uint
//   - input domain.UpdateNotifierConfigInput
func (_e *MockNotifierConfigService_Expecter) Update(id interface{}, input interface{}) *MockNotifierConfigService_Update_Call {
	return &MockNotifierConfigService_Update_Call{Call: _e.mock.On("Update", id, input)}
}

func (_c *MockNotifierConfigService_Update_Call) Run(run func(id uint, input domain.UpdateNotifierConfigInput)) *MockNotifierConfigService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(domain.UpdateNotifierConfigInput))
	})
	return _c
}

func (_c *MockNotifierConfigService_Update_Call) Return(_a0 *domain.NotifierConfig, _a1 error) *MockNotifierConfigService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotifierConfigService_Update_Call) RunAndReturn(run func(uint, domain.UpdateNotifierConfigInput) (*domain.NotifierConfig, error)) *MockNotifierConfigService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotifierConfigService creates a new instance of MockNotifierConfigService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifierConfigService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifierConfigService {
	mock := &MockNotifierConfigService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
