// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockNotifierConfigRepository is an autogenerated mock type for the NotifierConfigRepository type
type MockNotifierConfigRepository struct {
	mock.Mock
}

type MockNotifierConfigRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifierConfigRepository) EXPECT() *MockNotifierConfigRepository_Expecter {
	return &MockNotifierConfigRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: cfg
func (_m *MockNotifierConfigRepository) Create(cfg *domain.NotifierConfig) error {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.NotifierConfig) error); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifierConfigRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNotifierConfigRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - cfg *domain.NotifierConfig
func (_e *MockNotifierConfigRepository_Expecter) Create(cfg interface{}) *MockNotifierConfigRepository_Create_Call {
	return &MockNotifierConfigRepository_Create_Call{Call: _e.mock.On("Create", cfg)}
}

func (_c *MockNotifierConfigRepository_Create_Call) Run(run func(cfg *domain.NotifierConfig)) *MockNotifierConfigRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.NotifierConfig))
	})
	return _c
}

func (_c *MockNotifierConfigRepository_Create_Call) Return(_a0 error) *MockNotifierConfigRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifierConfigRepository_Create_Call) RunAndReturn(run func(*domain.NotifierConfig) error) *MockNotifierConfigRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockNotifierConfigRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifierConfigRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNotifierConfigRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockNotifierConfigRepository_Expecter) Delete(id interface{}) *MockNotifierConfigRepository_Delete_Call {
	return &MockNotifierConfigRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockNotifierConfigRepository_Delete_Call) Run(run func(id uint)) *MockNotifierConfigRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockNotifierConfigRepository_Delete_Call) Return(_a0 error) *MockNotifierConfigRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifierConfigRepository_Delete_Call) RunAndReturn(run func(uint) error) *MockNotifierConfigRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with no fields
func (_m *MockNotifierConfigRepository) FindAll() ([]domain.NotifierConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.NotifierConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.NotifierConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.NotifierConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.NotifierConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotifierConfigRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockNotifierConfigRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockNotifierConfigRepository_Expecter) FindAll() *MockNotifierConfigRepository_FindAll_Call {
	return &MockNotifierConfigRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockNotifierConfigRepository_FindAll_Call) Run(run func()) *MockNotifierConfigRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifierConfigRepository_FindAll_Call) Return(_a0 []domain.NotifierConfig, _a1 error) *MockNotifierConfigRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotifierConfigRepository_FindAll_Call) RunAndReturn(run func() ([]domain.NotifierConfig, error)) *MockNotifierConfigRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockNotifierConfigRepository) FindByID(id uint) (*domain.NotifierConfig, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.NotifierConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.NotifierConfig, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.NotifierConfig); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.NotifierConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotifierConfigRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockNotifierConfigRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint
func (_e *MockNotifierConfigRepository_Expecter) FindByID(id interface{}) *MockNotifierConfigRepository_FindByID_Call {
	return &MockNotifierConfigRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockNotifierConfigRepository_FindByID_Call) Run(run func(id uint)) *MockNotifierConfigRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockNotifierConfigRepository_FindByID_Call) Return(_a0 *domain.NotifierConfig, _a1 error) *MockNotifierConfigRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotifierConfigRepository_FindByID_Call) RunAndReturn(run func(uint) (*domain.NotifierConfig, error)) *MockNotifierConfigRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindEnabled provides a mock function with no fields
func (_m *MockNotifierConfigRepository) FindEnabled() ([]domain.NotifierConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindEnabled")
	}

	var r0 []domain.NotifierConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.NotifierConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.NotifierConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.NotifierConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotifierConfigRepository_FindEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindEnabled'
type MockNotifierConfigRepository_FindEnabled_Call struct {
	*mock.Call
}

// FindEnabled is a helper method to define mock.On call
func (_e *MockNotifierConfigRepository_Expecter) FindEnabled() *MockNotifierConfigRepository_FindEnabled_Call {
	return &MockNotifierConfigRepository_FindEnabled_Call{Call: _e.mock.On("FindEnabled")}
}

func (_c *MockNotifierConfigRepository_FindEnabled_Call) Run(run func()) *MockNotifierConfigRepository_FindEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifierConfigRepository_FindEnabled_Call) Return(_a0 []domain.NotifierConfig, _a1 error) *MockNotifierConfigRepository_FindEnabled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotifierConfigRepository_FindEnabled_Call) RunAndReturn(run func() ([]domain.NotifierConfig, error)) *MockNotifierConfigRepository_FindEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: cfg
func (_m *MockNotifierConfigRepository) Update(cfg *domain.NotifierConfig) error {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.NotifierConfig) error); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifierConfigRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockNotifierConfigRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - cfg *domain.NotifierConfig
func (_e *MockNotifierConfigRepository_Expecter) Update(cfg interface{}) *MockNotifierConfigRepository_Update_Call {
	return &MockNotifierConfigRepository_Update_Call{Call: _e.mock.On("Update", cfg)}
}

func (_c *MockNotifierConfigRepository_Update_Call) Run(run func(cfg *domain.NotifierConfig)) *MockNotifierConfigRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.NotifierConfig))
	})
	return _c
}

func (_c *MockNotifierConfigRepository_Update_Call) Return(_a0 error) *MockNotifierConfigRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifierConfigRepository_Update_Call) RunAndReturn(run func(*domain.NotifierConfig) error) *MockNotifierConfigRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotifierConfigRepository creates a new instance of MockNotifierConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifierConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifierConfigRepository {
	mock := &MockNotifierConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
