// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTrackerService is an autogenerated mock type for the TrackerService type
type MockTrackerService struct {
	mock.Mock
}

type MockTrackerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrackerService) EXPECT() *MockTrackerService_Expecter {
	return &MockTrackerService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: input
func (_m *MockTrackerService) Create(input domain.CreateTrackerInput) (*domain.Tracker, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Tracker
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.CreateTrackerInput) (*domain.Tracker, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(domain.CreateTrackerInput) *domain.Tracker); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tracker)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.CreateTrackerInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTrackerService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTrackerService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - input domain.CreateTrackerInput
func (_e *MockTrackerService_Expecter) Create(input interface{}) *MockTrackerService_Create_Call {
	return &MockTrackerService_Create_Call{Call: _e.mock.On("Create", input)}
}

func (_c *MockTrackerService_Create_Call) Run(run func(input domain.CreateTrackerInput)) *MockTrackerService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.CreateTrackerInput))
	})
	return _c
}

func (_c *MockTrackerService_Create_Call) Return(_a0 *domain.Tracker, _a1 error) *MockTrackerService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackerService_Create_Call) RunAndReturn(run func(domain.CreateTrackerInput) (*domain.Tracker, error)) *MockTrackerService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockTrackerService) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTrackerService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTrackerService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockTrackerService_Expecter) Delete(id interface{}) *MockTrackerService_Delete_Call {
	return &MockTrackerService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockTrackerService_Delete_Call) Run(run func(id uint)) *MockTrackerService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockTrackerService_Delete_Call) Return(_a0 error) *MockTrackerService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackerService_Delete_Call) RunAndReturn(run func(uint) error) *MockTrackerService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetActive provides a mock function with no fields
func (_m *MockTrackerService) GetActive() ([]domain.Tracker, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActive")
	}

	var r0 []domain.Tracker
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Tracker, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Tracker); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tracker)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTrackerService_GetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActive'
type MockTrackerService_GetActive_Call struct {
	*mock.Call
}

// GetActive is a helper method to define mock.On call
func (_e *MockTrackerService_Expecter) GetActive() *MockTrackerService_GetActive_Call {
	return &MockTrackerService_GetActive_Call{Call: _e.mock.On("GetActive")}
}

func (_c *MockTrackerService_GetActive_Call) Run(run func()) *MockTrackerService_GetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrackerService_GetActive_Call) Return(_a0 []domain.Tracker, _a1 error) *MockTrackerService_GetActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackerService_GetActive_Call) RunAndReturn(run func() ([]domain.Tracker, error)) *MockTrackerService_GetActive_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: opts
func (_m *MockTrackerService) GetAll(opts *domain.TrackerSortOptions) ([]domain.Tracker, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Tracker
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.TrackerSortOptions) ([]domain.Tracker, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*domain.TrackerSortOptions) []domain.Tracker); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tracker)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.TrackerSortOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTrackerService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTrackerService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - opts *domain.TrackerSortOptions
func (_e *MockTrackerService_Expecter) GetAll(opts interface{}) *MockTrackerService_GetAll_Call {
	return &MockTrackerService_GetAll_Call{Call: _e.mock.On("GetAll", opts)}
}

func (_c *MockTrackerService_GetAll_Call) Run(run func(opts *domain.TrackerSortOptions)) *MockTrackerService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.TrackerSortOptions))
	})
	return _c
}

func (_c *MockTrackerService_GetAll_Call) Return(_a0 []domain.Tracker, _a1 error) *MockTrackerService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackerService_GetAll_Call) RunAndReturn(run func(*domain.TrackerSortOptions) ([]domain.Tracker, error)) *MockTrackerService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockTrackerService) GetByID(id uint) (*domain.Tracker, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Tracker
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Tracker, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Tracker); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tracker)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTrackerService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTrackerService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockTrackerService_Expecter) GetByID(id interface{}) *MockTrackerService_GetByID_Call {
	return &MockTrackerService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockTrackerService_GetByID_Call) Run(run func(id uint)) *MockTrackerService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockTrackerService_GetByID_Call) Return(_a0 *domain.Tracker, _a1 error) *MockTrackerService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackerService_GetByID_Call) RunAndReturn(run func(uint) (*domain.Tracker, error)) *MockTrackerService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Test provides a mock function with given fields: scraperKey, credentialsJSON
func (_m *MockTrackerService) Test(scraperKey string, credentialsJSON string) error {
	ret := _m.Called(scraperKey, credentialsJSON)

	if len(ret) == 0 {
		panic("no return value specified for Test")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(scraperKey, credentialsJSON)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTrackerService_Test_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Test'
type MockTrackerService_Test_Call struct {
	*mock.Call
}

// Test is a helper method to define mock.On call
//   - scraperKey string
//   - credentialsJSON string
func (_e *MockTrackerService_Expecter) Test(scraperKey interface{}, credentialsJSON interface{}) *MockTrackerService_Test_Call {
	return &MockTrackerService_Test_Call{Call: _e.mock.On("Test", scraperKey, credentialsJSON)}
}

func (_c *MockTrackerService_Test_Call) Run(run func(scraperKey string, credentialsJSON string)) *MockTrackerService_Test_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockTrackerService_Test_Call) Return(_a0 error) *MockTrackerService_Test_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackerService_Test_Call) RunAndReturn(run func(string, string) error) *MockTrackerService_Test_Call {
	_c.Call.Return(run)
	return _c
}

// TestByID provides a mock function with given fields: id, credentialsOverride
func (_m *MockTrackerService) TestByID(id uint, credentialsOverride string) error {
	ret := _m.Called(id, credentialsOverride)

	if len(ret) == 0 {
		panic("no return value specified for TestByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = rf(id, credentialsOverride)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTrackerService_TestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestByID'
type MockTrackerService_TestByID_Call struct {
	*mock.Call
}

// TestByID is a helper method to define mock.On call
//   - id uint
//   - credentialsOverride string
func (_e *MockTrackerService_Expecter) TestByID(id interface{}, credentialsOverride interface{}) *MockTrackerService_TestByID_Call {
	return &MockTrackerService_TestByID_Call{Call: _e.mock.On("TestByID", id, credentialsOverride)}
}

func (_c *MockTrackerService_TestByID_Call) Run(run func(id uint, credentialsOverride string)) *MockTrackerService_TestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(string))
	})
	return _c
}

func (_c *MockTrackerService_TestByID_Call) Return(_a0 error) *MockTrackerService_TestByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackerService_TestByID_Call) RunAndReturn(run func(uint, string) error) *MockTrackerService_TestByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, input
func (_m *MockTrackerService) Update(id uint, input domain.UpdateTrackerInput) (*domain.Tracker, error) {
	ret := _m.Called(id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Tracker
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, domain.UpdateTrackerInput) (*domain.Tracker, error)); ok {
		return rf(id, input)
	}
	if rf, ok := ret.Get(0).(func(uint, domain.UpdateTrackerInput) *domain.Tracker); ok {
		r0 = rf(id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tracker)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, domain.UpdateTrackerInput) error); ok {
		r1 = rf(id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTrackerService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTrackerService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uint
//   - input domain.UpdateTrackerInput
func (_e *MockTrackerService_Expecter) Update(id interface{}, input interface{}) *MockTrackerService_Update_Call {
	return &MockTrackerService_Update_Call{Call: _e.mock.On("Update", id, input)}
}

func (_c *MockTrackerService_Update_Call) Run(run func(id uint, input domain.UpdateTrackerInput)) *MockTrackerService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(domain.UpdateTrackerInput))
	})
	return _c
}

func (_c *MockTrackerService_Update_Call) Return(_a0 *domain.Tracker, _a1 error) *MockTrackerService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackerService_Update_Call) RunAndReturn(run func(uint, domain.UpdateTrackerInput) (*domain.Tracker, error)) *MockTrackerService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTrackerService creates a new instance of MockTrackerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrackerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrackerService {
	mock := &MockTrackerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
