// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockReportRepository is an autogenerated mock type for the ReportRepository type
type MockReportRepository struct {
	mock.Mock
}

type MockReportRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportRepository) EXPECT() *MockReportRepository_Expecter {
	return &MockReportRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: report
func (_m *MockReportRepository) Create(report *domain.Report) error {
	ret := _m.Called(report)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Report) error); ok {
		r0 = rf(report)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type MockReportRepository_Create_Call struct{ *mock.Call }

func (_e *MockReportRepository_Expecter) Create(report interface{}) *MockReportRepository_Create_Call {
	return &MockReportRepository_Create_Call{Call: _e.mock.On("Create", report)}
}

func (_c *MockReportRepository_Create_Call) Run(run func(report *domain.Report)) *MockReportRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(*domain.Report)) })
	return _c
}

func (_c *MockReportRepository_Create_Call) Return(_a0 error) *MockReportRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockReportRepository) Delete(id uint) error {
	ret := _m.Called(id)
	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type MockReportRepository_Delete_Call struct{ *mock.Call }

func (_e *MockReportRepository_Expecter) Delete(id interface{}) *MockReportRepository_Delete_Call {
	return &MockReportRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockReportRepository_Delete_Call) Run(run func(id uint)) *MockReportRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(uint)) })
	return _c
}

func (_c *MockReportRepository_Delete_Call) Return(_a0 error) *MockReportRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

// FindAll provides a mock function with no fields
func (_m *MockReportRepository) FindAll() ([]domain.Report, error) {
	ret := _m.Called()
	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}
	var r0 []domain.Report
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Report, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Report); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Report)
		}
	}
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockReportRepository_FindAll_Call struct{ *mock.Call }

func (_e *MockReportRepository_Expecter) FindAll() *MockReportRepository_FindAll_Call {
	return &MockReportRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockReportRepository_FindAll_Call) Run(run func()) *MockReportRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) { run() })
	return _c
}

func (_c *MockReportRepository_FindAll_Call) Return(_a0 []domain.Report, _a1 error) *MockReportRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockReportRepository) FindByID(id uint) (*domain.Report, error) {
	ret := _m.Called(id)
	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}
	var r0 *domain.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Report, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Report); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Report)
		}
	}
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockReportRepository_FindByID_Call struct{ *mock.Call }

func (_e *MockReportRepository_Expecter) FindByID(id interface{}) *MockReportRepository_FindByID_Call {
	return &MockReportRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockReportRepository_FindByID_Call) Run(run func(id uint)) *MockReportRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(uint)) })
	return _c
}

func (_c *MockReportRepository_FindByID_Call) Return(_a0 *domain.Report, _a1 error) *MockReportRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Update provides a mock function with given fields: report
func (_m *MockReportRepository) Update(report *domain.Report) error {
	ret := _m.Called(report)
	if len(ret) == 0 {
		panic("no return value specified for Update")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Report) error); ok {
		r0 = rf(report)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type MockReportRepository_Update_Call struct{ *mock.Call }

func (_e *MockReportRepository_Expecter) Update(report interface{}) *MockReportRepository_Update_Call {
	return &MockReportRepository_Update_Call{Call: _e.mock.On("Update", report)}
}

func (_c *MockReportRepository_Update_Call) Run(run func(report *domain.Report)) *MockReportRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(*domain.Report)) })
	return _c
}

func (_c *MockReportRepository_Update_Call) Return(_a0 error) *MockReportRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

// UpdateLastSentAt provides a mock function with given fields: id, sentAt
func (_m *MockReportRepository) UpdateLastSentAt(id uint, sentAt time.Time) error {
	ret := _m.Called(id, sentAt)
	if len(ret) == 0 {
		panic("no return value specified for UpdateLastSentAt")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(uint, time.Time) error); ok {
		r0 = rf(id, sentAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type MockReportRepository_UpdateLastSentAt_Call struct{ *mock.Call }

func (_e *MockReportRepository_Expecter) UpdateLastSentAt(id interface{}, sentAt interface{}) *MockReportRepository_UpdateLastSentAt_Call {
	return &MockReportRepository_UpdateLastSentAt_Call{Call: _e.mock.On("UpdateLastSentAt", id, sentAt)}
}

func (_c *MockReportRepository_UpdateLastSentAt_Call) Run(run func(id uint, sentAt time.Time)) *MockReportRepository_UpdateLastSentAt_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(uint), args[1].(time.Time)) })
	return _c
}

func (_c *MockReportRepository_UpdateLastSentAt_Call) Return(_a0 error) *MockReportRepository_UpdateLastSentAt_Call {
	_c.Call.Return(_a0)
	return _c
}

// UpdateNotifierConfigs provides a mock function with given fields: reportID, configIDs
func (_m *MockReportRepository) UpdateNotifierConfigs(reportID uint, configIDs []uint) error {
	ret := _m.Called(reportID, configIDs)
	if len(ret) == 0 {
		panic("no return value specified for UpdateNotifierConfigs")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(uint, []uint) error); ok {
		r0 = rf(reportID, configIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type MockReportRepository_UpdateNotifierConfigs_Call struct{ *mock.Call }

func (_e *MockReportRepository_Expecter) UpdateNotifierConfigs(reportID interface{}, configIDs interface{}) *MockReportRepository_UpdateNotifierConfigs_Call {
	return &MockReportRepository_UpdateNotifierConfigs_Call{Call: _e.mock.On("UpdateNotifierConfigs", reportID, configIDs)}
}

func (_c *MockReportRepository_UpdateNotifierConfigs_Call) Run(run func(reportID uint, configIDs []uint)) *MockReportRepository_UpdateNotifierConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(uint), args[1].([]uint)) })
	return _c
}

func (_c *MockReportRepository_UpdateNotifierConfigs_Call) Return(_a0 error) *MockReportRepository_UpdateNotifierConfigs_Call {
	_c.Call.Return(_a0)
	return _c
}

// NewMockReportRepository creates a new instance of MockReportRepository.
func NewMockReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportRepository {
	mock := &MockReportRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
