// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTrackerScraper is an autogenerated mock type for the TrackerScraper type
type MockTrackerScraper struct {
	mock.Mock
}

type MockTrackerScraper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrackerScraper) EXPECT() *MockTrackerScraper_Expecter {
	return &MockTrackerScraper_Expecter{mock: &_m.Mock}
}

// CredentialFields provides a mock function with no fields
func (_m *MockTrackerScraper) CredentialFields() []domain.CredentialField {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CredentialFields")
	}

	var r0 []domain.CredentialField
	if rf, ok := ret.Get(0).(func() []domain.CredentialField); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CredentialField)
		}
	}

	return r0
}

// MockTrackerScraper_CredentialFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CredentialFields'
type MockTrackerScraper_CredentialFields_Call struct {
	*mock.Call
}

// CredentialFields is a helper method to define mock.On call
func (_e *MockTrackerScraper_Expecter) CredentialFields() *MockTrackerScraper_CredentialFields_Call {
	return &MockTrackerScraper_CredentialFields_Call{Call: _e.mock.On("CredentialFields")}
}

func (_c *MockTrackerScraper_CredentialFields_Call) Run(run func()) *MockTrackerScraper_CredentialFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrackerScraper_CredentialFields_Call) Return(_a0 []domain.CredentialField) *MockTrackerScraper_CredentialFields_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackerScraper_CredentialFields_Call) RunAndReturn(run func() []domain.CredentialField) *MockTrackerScraper_CredentialFields_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function with given fields: ctx, tracker
func (_m *MockTrackerScraper) Fetch(ctx context.Context, tracker domain.Tracker) (*domain.TrackerStats, error) {
	ret := _m.Called(ctx, tracker)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 *domain.TrackerStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Tracker) (*domain.TrackerStats, error)); ok {
		return rf(ctx, tracker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Tracker) *domain.TrackerStats); ok {
		r0 = rf(ctx, tracker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TrackerStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Tracker) error); ok {
		r1 = rf(ctx, tracker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTrackerScraper_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockTrackerScraper_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - tracker domain.Tracker
func (_e *MockTrackerScraper_Expecter) Fetch(ctx interface{}, tracker interface{}) *MockTrackerScraper_Fetch_Call {
	return &MockTrackerScraper_Fetch_Call{Call: _e.mock.On("Fetch", ctx, tracker)}
}

func (_c *MockTrackerScraper_Fetch_Call) Run(run func(ctx context.Context, tracker domain.Tracker)) *MockTrackerScraper_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Tracker))
	})
	return _c
}

func (_c *MockTrackerScraper_Fetch_Call) Return(_a0 *domain.TrackerStats, _a1 error) *MockTrackerScraper_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackerScraper_Fetch_Call) RunAndReturn(run func(context.Context, domain.Tracker) (*domain.TrackerStats, error)) *MockTrackerScraper_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Key provides a mock function with no fields
func (_m *MockTrackerScraper) Key() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Key")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTrackerScraper_Key_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Key'
type MockTrackerScraper_Key_Call struct {
	*mock.Call
}

// Key is a helper method to define mock.On call
func (_e *MockTrackerScraper_Expecter) Key() *MockTrackerScraper_Key_Call {
	return &MockTrackerScraper_Key_Call{Call: _e.mock.On("Key")}
}

func (_c *MockTrackerScraper_Key_Call) Run(run func()) *MockTrackerScraper_Key_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrackerScraper_Key_Call) Return(_a0 string) *MockTrackerScraper_Key_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackerScraper_Key_Call) RunAndReturn(run func() string) *MockTrackerScraper_Key_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTrackerScraper creates a new instance of MockTrackerScraper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrackerScraper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrackerScraper {
	mock := &MockTrackerScraper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
