// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockNotifierBuilder is an autogenerated mock type for the NotifierBuilder type
type MockNotifierBuilder struct {
	mock.Mock
}

type MockNotifierBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifierBuilder) EXPECT() *MockNotifierBuilder_Expecter {
	return &MockNotifierBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function with given fields: cfgType, cfgJSON
func (_m *MockNotifierBuilder) Build(cfgType string, cfgJSON string) (domain.Notifier, error) {
	ret := _m.Called(cfgType, cfgJSON)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 domain.Notifier
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (domain.Notifier, error)); ok {
		return rf(cfgType, cfgJSON)
	}
	if rf, ok := ret.Get(0).(func(string, string) domain.Notifier); ok {
		r0 = rf(cfgType, cfgJSON)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Notifier)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(cfgType, cfgJSON)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotifierBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockNotifierBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - cfgType string
//   - cfgJSON string
func (_e *MockNotifierBuilder_Expecter) Build(cfgType interface{}, cfgJSON interface{}) *MockNotifierBuilder_Build_Call {
	return &MockNotifierBuilder_Build_Call{Call: _e.mock.On("Build", cfgType, cfgJSON)}
}

func (_c *MockNotifierBuilder_Build_Call) Run(run func(cfgType string, cfgJSON string)) *MockNotifierBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockNotifierBuilder_Build_Call) Return(_a0 domain.Notifier, _a1 error) *MockNotifierBuilder_Build_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotifierBuilder_Build_Call) RunAndReturn(run func(string, string) (domain.Notifier, error)) *MockNotifierBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotifierBuilder creates a new instance of MockNotifierBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifierBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifierBuilder {
	mock := &MockNotifierBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
