// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockMultisolverrConfigRepository is an autogenerated mock type for the MultisolverrConfigRepository type
type MockMultisolverrConfigRepository struct {
	mock.Mock
}

type MockMultisolverrConfigRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMultisolverrConfigRepository) EXPECT() *MockMultisolverrConfigRepository_Expecter {
	return &MockMultisolverrConfigRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with no fields
func (_m *MockMultisolverrConfigRepository) Get() (*domain.MultisolverrConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.MultisolverrConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() (*domain.MultisolverrConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *domain.MultisolverrConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MultisolverrConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMultisolverrConfigRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMultisolverrConfigRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockMultisolverrConfigRepository_Expecter) Get() *MockMultisolverrConfigRepository_Get_Call {
	return &MockMultisolverrConfigRepository_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockMultisolverrConfigRepository_Get_Call) Run(run func()) *MockMultisolverrConfigRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMultisolverrConfigRepository_Get_Call) Return(_a0 *domain.MultisolverrConfig, _a1 error) *MockMultisolverrConfigRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMultisolverrConfigRepository_Get_Call) RunAndReturn(run func() (*domain.MultisolverrConfig, error)) *MockMultisolverrConfigRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: cfg
func (_m *MockMultisolverrConfigRepository) Update(cfg *domain.MultisolverrConfig) error {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.MultisolverrConfig) error); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMultisolverrConfigRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMultisolverrConfigRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - cfg *domain.MultisolverrConfig
func (_e *MockMultisolverrConfigRepository_Expecter) Update(cfg interface{}) *MockMultisolverrConfigRepository_Update_Call {
	return &MockMultisolverrConfigRepository_Update_Call{Call: _e.mock.On("Update", cfg)}
}

func (_c *MockMultisolverrConfigRepository_Update_Call) Run(run func(cfg *domain.MultisolverrConfig)) *MockMultisolverrConfigRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.MultisolverrConfig))
	})
	return _c
}

func (_c *MockMultisolverrConfigRepository_Update_Call) Return(_a0 error) *MockMultisolverrConfigRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMultisolverrConfigRepository_Update_Call) RunAndReturn(run func(*domain.MultisolverrConfig) error) *MockMultisolverrConfigRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMultisolverrConfigRepository creates a new instance of MockMultisolverrConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMultisolverrConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMultisolverrConfigRepository {
	mock := &MockMultisolverrConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
