// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

type MockAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepository) EXPECT() *MockAuthRepository_Expecter {
	return &MockAuthRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: username, passwordHash, jwtSecret
func (_m *MockAuthRepository) Create(username string, passwordHash string, jwtSecret string) (*domain.AppCredential, error) {
	ret := _m.Called(username, passwordHash, jwtSecret)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.AppCredential
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*domain.AppCredential, error)); ok {
		return rf(username, passwordHash, jwtSecret)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *domain.AppCredential); ok {
		r0 = rf(username, passwordHash, jwtSecret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AppCredential)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(username, passwordHash, jwtSecret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuthRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - username string
//   - passwordHash string
//   - jwtSecret string
func (_e *MockAuthRepository_Expecter) Create(username interface{}, passwordHash interface{}, jwtSecret interface{}) *MockAuthRepository_Create_Call {
	return &MockAuthRepository_Create_Call{Call: _e.mock.On("Create", username, passwordHash, jwtSecret)}
}

func (_c *MockAuthRepository_Create_Call) Run(run func(username string, passwordHash string, jwtSecret string)) *MockAuthRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthRepository_Create_Call) Return(_a0 *domain.AppCredential, _a1 error) *MockAuthRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthRepository_Create_Call) RunAndReturn(run func(string, string, string) (*domain.AppCredential, error)) *MockAuthRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with no fields
func (_m *MockAuthRepository) Find() (*domain.AppCredential, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *domain.AppCredential
	var r1 error
	if rf, ok := ret.Get(0).(func() (*domain.AppCredential, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *domain.AppCredential); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AppCredential)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockAuthRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
func (_e *MockAuthRepository_Expecter) Find() *MockAuthRepository_Find_Call {
	return &MockAuthRepository_Find_Call{Call: _e.mock.On("Find")}
}

func (_c *MockAuthRepository_Find_Call) Run(run func()) *MockAuthRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthRepository_Find_Call) Return(_a0 *domain.AppCredential, _a1 error) *MockAuthRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthRepository_Find_Call) RunAndReturn(run func() (*domain.AppCredential, error)) *MockAuthRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, username, passwordHash
func (_m *MockAuthRepository) Update(id uint, username string, passwordHash string) error {
	ret := _m.Called(id, username, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string, string) error); ok {
		r0 = rf(id, username, passwordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAuthRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uint
//   - username string
//   - passwordHash string
func (_e *MockAuthRepository_Expecter) Update(id interface{}, username interface{}, passwordHash interface{}) *MockAuthRepository_Update_Call {
	return &MockAuthRepository_Update_Call{Call: _e.mock.On("Update", id, username, passwordHash)}
}

func (_c *MockAuthRepository_Update_Call) Run(run func(id uint, username string, passwordHash string)) *MockAuthRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthRepository_Update_Call) Return(_a0 error) *MockAuthRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthRepository_Update_Call) RunAndReturn(run func(uint, string, string) error) *MockAuthRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLanguage provides a mock function with given fields: id, language
func (_m *MockAuthRepository) UpdateLanguage(id uint, language string) error {
	ret := _m.Called(id, language)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLanguage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = rf(id, language)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthRepository_UpdateLanguage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLanguage'
type MockAuthRepository_UpdateLanguage_Call struct {
	*mock.Call
}

// UpdateLanguage is a helper method to define mock.On call
//   - id uint
//   - language string
func (_e *MockAuthRepository_Expecter) UpdateLanguage(id interface{}, language interface{}) *MockAuthRepository_UpdateLanguage_Call {
	return &MockAuthRepository_UpdateLanguage_Call{Call: _e.mock.On("UpdateLanguage", id, language)}
}

func (_c *MockAuthRepository_UpdateLanguage_Call) Run(run func(id uint, language string)) *MockAuthRepository_UpdateLanguage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(string))
	})
	return _c
}

func (_c *MockAuthRepository_UpdateLanguage_Call) Return(_a0 error) *MockAuthRepository_UpdateLanguage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthRepository_UpdateLanguage_Call) RunAndReturn(run func(uint, string) error) *MockAuthRepository_UpdateLanguage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
