// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAlertConfigRepository is an autogenerated mock type for the AlertConfigRepository type
type MockAlertConfigRepository struct {
	mock.Mock
}

type MockAlertConfigRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlertConfigRepository) EXPECT() *MockAlertConfigRepository_Expecter {
	return &MockAlertConfigRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: config
func (_m *MockAlertConfigRepository) Create(config *domain.AlertConfig) error {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.AlertConfig) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertConfigRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAlertConfigRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - config *domain.AlertConfig
func (_e *MockAlertConfigRepository_Expecter) Create(config interface{}) *MockAlertConfigRepository_Create_Call {
	return &MockAlertConfigRepository_Create_Call{Call: _e.mock.On("Create", config)}
}

func (_c *MockAlertConfigRepository_Create_Call) Run(run func(config *domain.AlertConfig)) *MockAlertConfigRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.AlertConfig))
	})
	return _c
}

func (_c *MockAlertConfigRepository_Create_Call) Return(_a0 error) *MockAlertConfigRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertConfigRepository_Create_Call) RunAndReturn(run func(*domain.AlertConfig) error) *MockAlertConfigRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockAlertConfigRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertConfigRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAlertConfigRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockAlertConfigRepository_Expecter) Delete(id interface{}) *MockAlertConfigRepository_Delete_Call {
	return &MockAlertConfigRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockAlertConfigRepository_Delete_Call) Run(run func(id uint)) *MockAlertConfigRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockAlertConfigRepository_Delete_Call) Return(_a0 error) *MockAlertConfigRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertConfigRepository_Delete_Call) RunAndReturn(run func(uint) error) *MockAlertConfigRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with no fields
func (_m *MockAlertConfigRepository) FindAll() ([]domain.AlertConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.AlertConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.AlertConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.AlertConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AlertConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertConfigRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockAlertConfigRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockAlertConfigRepository_Expecter) FindAll() *MockAlertConfigRepository_FindAll_Call {
	return &MockAlertConfigRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockAlertConfigRepository_FindAll_Call) Run(run func()) *MockAlertConfigRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAlertConfigRepository_FindAll_Call) Return(_a0 []domain.AlertConfig, _a1 error) *MockAlertConfigRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertConfigRepository_FindAll_Call) RunAndReturn(run func() ([]domain.AlertConfig, error)) *MockAlertConfigRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllEnabled provides a mock function with no fields
func (_m *MockAlertConfigRepository) FindAllEnabled() ([]domain.AlertConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAllEnabled")
	}

	var r0 []domain.AlertConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.AlertConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.AlertConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AlertConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertConfigRepository_FindAllEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllEnabled'
type MockAlertConfigRepository_FindAllEnabled_Call struct {
	*mock.Call
}

// FindAllEnabled is a helper method to define mock.On call
func (_e *MockAlertConfigRepository_Expecter) FindAllEnabled() *MockAlertConfigRepository_FindAllEnabled_Call {
	return &MockAlertConfigRepository_FindAllEnabled_Call{Call: _e.mock.On("FindAllEnabled")}
}

func (_c *MockAlertConfigRepository_FindAllEnabled_Call) Run(run func()) *MockAlertConfigRepository_FindAllEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAlertConfigRepository_FindAllEnabled_Call) Return(_a0 []domain.AlertConfig, _a1 error) *MockAlertConfigRepository_FindAllEnabled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertConfigRepository_FindAllEnabled_Call) RunAndReturn(run func() ([]domain.AlertConfig, error)) *MockAlertConfigRepository_FindAllEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockAlertConfigRepository) FindByID(id uint) (*domain.AlertConfig, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.AlertConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.AlertConfig, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.AlertConfig); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AlertConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertConfigRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockAlertConfigRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint
func (_e *MockAlertConfigRepository_Expecter) FindByID(id interface{}) *MockAlertConfigRepository_FindByID_Call {
	return &MockAlertConfigRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockAlertConfigRepository_FindByID_Call) Run(run func(id uint)) *MockAlertConfigRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockAlertConfigRepository_FindByID_Call) Return(_a0 *domain.AlertConfig, _a1 error) *MockAlertConfigRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertConfigRepository_FindByID_Call) RunAndReturn(run func(uint) (*domain.AlertConfig, error)) *MockAlertConfigRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSentState provides a mock function with given fields: alertConfigID, trackerID
func (_m *MockAlertConfigRepository) GetSentState(alertConfigID uint, trackerID uint) (bool, error) {
	ret := _m.Called(alertConfigID, trackerID)

	if len(ret) == 0 {
		panic("no return value specified for GetSentState")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) (bool, error)); ok {
		return rf(alertConfigID, trackerID)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) bool); ok {
		r0 = rf(alertConfigID, trackerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(alertConfigID, trackerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertConfigRepository_GetSentState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSentState'
type MockAlertConfigRepository_GetSentState_Call struct {
	*mock.Call
}

// GetSentState is a helper method to define mock.On call
//   - alertConfigID uint
//   - trackerID uint
func (_e *MockAlertConfigRepository_Expecter) GetSentState(alertConfigID interface{}, trackerID interface{}) *MockAlertConfigRepository_GetSentState_Call {
	return &MockAlertConfigRepository_GetSentState_Call{Call: _e.mock.On("GetSentState", alertConfigID, trackerID)}
}

func (_c *MockAlertConfigRepository_GetSentState_Call) Run(run func(alertConfigID uint, trackerID uint)) *MockAlertConfigRepository_GetSentState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint))
	})
	return _c
}

func (_c *MockAlertConfigRepository_GetSentState_Call) Return(_a0 bool, _a1 error) *MockAlertConfigRepository_GetSentState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertConfigRepository_GetSentState_Call) RunAndReturn(run func(uint, uint) (bool, error)) *MockAlertConfigRepository_GetSentState_Call {
	_c.Call.Return(run)
	return _c
}

// SetSentState provides a mock function with given fields: alertConfigID, trackerID, sent
func (_m *MockAlertConfigRepository) SetSentState(alertConfigID uint, trackerID uint, sent bool) error {
	ret := _m.Called(alertConfigID, trackerID, sent)

	if len(ret) == 0 {
		panic("no return value specified for SetSentState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint, bool) error); ok {
		r0 = rf(alertConfigID, trackerID, sent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertConfigRepository_SetSentState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSentState'
type MockAlertConfigRepository_SetSentState_Call struct {
	*mock.Call
}

// SetSentState is a helper method to define mock.On call
//   - alertConfigID uint
//   - trackerID uint
//   - sent bool
func (_e *MockAlertConfigRepository_Expecter) SetSentState(alertConfigID interface{}, trackerID interface{}, sent interface{}) *MockAlertConfigRepository_SetSentState_Call {
	return &MockAlertConfigRepository_SetSentState_Call{Call: _e.mock.On("SetSentState", alertConfigID, trackerID, sent)}
}

func (_c *MockAlertConfigRepository_SetSentState_Call) Run(run func(alertConfigID uint, trackerID uint, sent bool)) *MockAlertConfigRepository_SetSentState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint), args[2].(bool))
	})
	return _c
}

func (_c *MockAlertConfigRepository_SetSentState_Call) Return(_a0 error) *MockAlertConfigRepository_SetSentState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertConfigRepository_SetSentState_Call) RunAndReturn(run func(uint, uint, bool) error) *MockAlertConfigRepository_SetSentState_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: config
func (_m *MockAlertConfigRepository) Update(config *domain.AlertConfig) error {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.AlertConfig) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertConfigRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAlertConfigRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - config *domain.AlertConfig
func (_e *MockAlertConfigRepository_Expecter) Update(config interface{}) *MockAlertConfigRepository_Update_Call {
	return &MockAlertConfigRepository_Update_Call{Call: _e.mock.On("Update", config)}
}

func (_c *MockAlertConfigRepository_Update_Call) Run(run func(config *domain.AlertConfig)) *MockAlertConfigRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.AlertConfig))
	})
	return _c
}

func (_c *MockAlertConfigRepository_Update_Call) Return(_a0 error) *MockAlertConfigRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertConfigRepository_Update_Call) RunAndReturn(run func(*domain.AlertConfig) error) *MockAlertConfigRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNotifierConfigs provides a mock function with given fields: alertConfigID, configIDs
func (_m *MockAlertConfigRepository) UpdateNotifierConfigs(alertConfigID uint, configIDs []uint) error {
	ret := _m.Called(alertConfigID, configIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotifierConfigs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, []uint) error); ok {
		r0 = rf(alertConfigID, configIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertConfigRepository_UpdateNotifierConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNotifierConfigs'
type MockAlertConfigRepository_UpdateNotifierConfigs_Call struct {
	*mock.Call
}

// UpdateNotifierConfigs is a helper method to define mock.On call
//   - alertConfigID uint
//   - configIDs []uint
func (_e *MockAlertConfigRepository_Expecter) UpdateNotifierConfigs(alertConfigID interface{}, configIDs interface{}) *MockAlertConfigRepository_UpdateNotifierConfigs_Call {
	return &MockAlertConfigRepository_UpdateNotifierConfigs_Call{Call: _e.mock.On("UpdateNotifierConfigs", alertConfigID, configIDs)}
}

func (_c *MockAlertConfigRepository_UpdateNotifierConfigs_Call) Run(run func(alertConfigID uint, configIDs []uint)) *MockAlertConfigRepository_UpdateNotifierConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].([]uint))
	})
	return _c
}

func (_c *MockAlertConfigRepository_UpdateNotifierConfigs_Call) Return(_a0 error) *MockAlertConfigRepository_UpdateNotifierConfigs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertConfigRepository_UpdateNotifierConfigs_Call) RunAndReturn(run func(uint, []uint) error) *MockAlertConfigRepository_UpdateNotifierConfigs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTrackers provides a mock function with given fields: alertConfigID, trackerIDs
func (_m *MockAlertConfigRepository) UpdateTrackers(alertConfigID uint, trackerIDs []uint) error {
	ret := _m.Called(alertConfigID, trackerIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTrackers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, []uint) error); ok {
		r0 = rf(alertConfigID, trackerIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertConfigRepository_UpdateTrackers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTrackers'
type MockAlertConfigRepository_UpdateTrackers_Call struct {
	*mock.Call
}

// UpdateTrackers is a helper method to define mock.On call
//   - alertConfigID uint
//   - trackerIDs []uint
func (_e *MockAlertConfigRepository_Expecter) UpdateTrackers(alertConfigID interface{}, trackerIDs interface{}) *MockAlertConfigRepository_UpdateTrackers_Call {
	return &MockAlertConfigRepository_UpdateTrackers_Call{Call: _e.mock.On("UpdateTrackers", alertConfigID, trackerIDs)}
}

func (_c *MockAlertConfigRepository_UpdateTrackers_Call) Run(run func(alertConfigID uint, trackerIDs []uint)) *MockAlertConfigRepository_UpdateTrackers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].([]uint))
	})
	return _c
}

func (_c *MockAlertConfigRepository_UpdateTrackers_Call) Return(_a0 error) *MockAlertConfigRepository_UpdateTrackers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertConfigRepository_UpdateTrackers_Call) RunAndReturn(run func(uint, []uint) error) *MockAlertConfigRepository_UpdateTrackers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlertConfigRepository creates a new instance of MockAlertConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlertConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlertConfigRepository {
	mock := &MockAlertConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
