// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRefresher is an autogenerated mock type for the Refresher type
type MockRefresher struct {
	mock.Mock
}

type MockRefresher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefresher) EXPECT() *MockRefresher_Expecter {
	return &MockRefresher_Expecter{mock: &_m.Mock}
}

// Schedule provides a mock function with given fields: tracker
func (_m *MockRefresher) Schedule(tracker domain.Tracker) error {
	ret := _m.Called(tracker)

	if len(ret) == 0 {
		panic("no return value specified for Schedule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Tracker) error); ok {
		r0 = rf(tracker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefresher_Schedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Schedule'
type MockRefresher_Schedule_Call struct {
	*mock.Call
}

// Schedule is a helper method to define mock.On call
//   - tracker domain.Tracker
func (_e *MockRefresher_Expecter) Schedule(tracker interface{}) *MockRefresher_Schedule_Call {
	return &MockRefresher_Schedule_Call{Call: _e.mock.On("Schedule", tracker)}
}

func (_c *MockRefresher_Schedule_Call) Run(run func(tracker domain.Tracker)) *MockRefresher_Schedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Tracker))
	})
	return _c
}

func (_c *MockRefresher_Schedule_Call) Return(_a0 error) *MockRefresher_Schedule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefresher_Schedule_Call) RunAndReturn(run func(domain.Tracker) error) *MockRefresher_Schedule_Call {
	_c.Call.Return(run)
	return _c
}

// Unschedule provides a mock function with given fields: trackerID
func (_m *MockRefresher) Unschedule(trackerID uint) {
	_m.Called(trackerID)
}

// MockRefresher_Unschedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unschedule'
type MockRefresher_Unschedule_Call struct {
	*mock.Call
}

// Unschedule is a helper method to define mock.On call
//   - trackerID uint
func (_e *MockRefresher_Expecter) Unschedule(trackerID interface{}) *MockRefresher_Unschedule_Call {
	return &MockRefresher_Unschedule_Call{Call: _e.mock.On("Unschedule", trackerID)}
}

func (_c *MockRefresher_Unschedule_Call) Run(run func(trackerID uint)) *MockRefresher_Unschedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockRefresher_Unschedule_Call) Return() *MockRefresher_Unschedule_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRefresher_Unschedule_Call) RunAndReturn(run func(uint)) *MockRefresher_Unschedule_Call {
	_c.Run(run)
	return _c
}

// NewMockRefresher creates a new instance of MockRefresher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefresher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefresher {
	mock := &MockRefresher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
