// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRefreshService is an autogenerated mock type for the RefreshService type
type MockRefreshService struct {
	mock.Mock
}

type MockRefreshService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshService) EXPECT() *MockRefreshService_Expecter {
	return &MockRefreshService_Expecter{mock: &_m.Mock}
}

// RefreshAll provides a mock function with given fields: ctx
func (_m *MockRefreshService) RefreshAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshService_RefreshAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAll'
type MockRefreshService_RefreshAll_Call struct {
	*mock.Call
}

// RefreshAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRefreshService_Expecter) RefreshAll(ctx interface{}) *MockRefreshService_RefreshAll_Call {
	return &MockRefreshService_RefreshAll_Call{Call: _e.mock.On("RefreshAll", ctx)}
}

func (_c *MockRefreshService_RefreshAll_Call) Run(run func(ctx context.Context)) *MockRefreshService_RefreshAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRefreshService_RefreshAll_Call) Return(_a0 error) *MockRefreshService_RefreshAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshService_RefreshAll_Call) RunAndReturn(run func(context.Context) error) *MockRefreshService_RefreshAll_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTracker provides a mock function with given fields: ctx, trackerID
func (_m *MockRefreshService) RefreshTracker(ctx context.Context, trackerID uint) error {
	ret := _m.Called(ctx, trackerID)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTracker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, trackerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshService_RefreshTracker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTracker'
type MockRefreshService_RefreshTracker_Call struct {
	*mock.Call
}

// RefreshTracker is a helper method to define mock.On call
//   - ctx context.Context
//   - trackerID uint
func (_e *MockRefreshService_Expecter) RefreshTracker(ctx interface{}, trackerID interface{}) *MockRefreshService_RefreshTracker_Call {
	return &MockRefreshService_RefreshTracker_Call{Call: _e.mock.On("RefreshTracker", ctx, trackerID)}
}

func (_c *MockRefreshService_RefreshTracker_Call) Run(run func(ctx context.Context, trackerID uint)) *MockRefreshService_RefreshTracker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRefreshService_RefreshTracker_Call) Return(_a0 error) *MockRefreshService_RefreshTracker_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshService_RefreshTracker_Call) RunAndReturn(run func(context.Context, uint) error) *MockRefreshService_RefreshTracker_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshService creates a new instance of MockRefreshService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshService {
	mock := &MockRefreshService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
