// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockStatsService is an autogenerated mock type for the StatsService type
type MockStatsService struct {
	mock.Mock
}

type MockStatsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatsService) EXPECT() *MockStatsService_Expecter {
	return &MockStatsService_Expecter{mock: &_m.Mock}
}

// DeleteEntry provides a mock function with given fields: statID, trackerID
func (_m *MockStatsService) DeleteEntry(statID uint, trackerID uint) error {
	ret := _m.Called(statID, trackerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(statID, trackerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStatsService_DeleteEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEntry'
type MockStatsService_DeleteEntry_Call struct {
	*mock.Call
}

// DeleteEntry is a helper method to define mock.On call
//   - statID uint
//   - trackerID uint
func (_e *MockStatsService_Expecter) DeleteEntry(statID interface{}, trackerID interface{}) *MockStatsService_DeleteEntry_Call {
	return &MockStatsService_DeleteEntry_Call{Call: _e.mock.On("DeleteEntry", statID, trackerID)}
}

func (_c *MockStatsService_DeleteEntry_Call) Run(run func(statID uint, trackerID uint)) *MockStatsService_DeleteEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint))
	})
	return _c
}

func (_c *MockStatsService_DeleteEntry_Call) Return(_a0 error) *MockStatsService_DeleteEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStatsService_DeleteEntry_Call) RunAndReturn(run func(uint, uint) error) *MockStatsService_DeleteEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetDashboard provides a mock function with no fields
func (_m *MockStatsService) GetDashboard() ([]domain.DashboardEntry, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDashboard")
	}

	var r0 []domain.DashboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.DashboardEntry, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.DashboardEntry); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DashboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsService_GetDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDashboard'
type MockStatsService_GetDashboard_Call struct {
	*mock.Call
}

// GetDashboard is a helper method to define mock.On call
func (_e *MockStatsService_Expecter) GetDashboard() *MockStatsService_GetDashboard_Call {
	return &MockStatsService_GetDashboard_Call{Call: _e.mock.On("GetDashboard")}
}

func (_c *MockStatsService_GetDashboard_Call) Run(run func()) *MockStatsService_GetDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStatsService_GetDashboard_Call) Return(_a0 []domain.DashboardEntry, _a1 error) *MockStatsService_GetDashboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsService_GetDashboard_Call) RunAndReturn(run func() ([]domain.DashboardEntry, error)) *MockStatsService_GetDashboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistory provides a mock function with given fields: trackerID, limit
func (_m *MockStatsService) GetHistory(trackerID uint, limit int) ([]domain.TrackerStats, error) {
	ret := _m.Called(trackerID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []domain.TrackerStats
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, int) ([]domain.TrackerStats, error)); ok {
		return rf(trackerID, limit)
	}
	if rf, ok := ret.Get(0).(func(uint, int) []domain.TrackerStats); ok {
		r0 = rf(trackerID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TrackerStats)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int) error); ok {
		r1 = rf(trackerID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsService_GetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistory'
type MockStatsService_GetHistory_Call struct {
	*mock.Call
}

// GetHistory is a helper method to define mock.On call
//   - trackerID uint
//   - limit int
func (_e *MockStatsService_Expecter) GetHistory(trackerID interface{}, limit interface{}) *MockStatsService_GetHistory_Call {
	return &MockStatsService_GetHistory_Call{Call: _e.mock.On("GetHistory", trackerID, limit)}
}

func (_c *MockStatsService_GetHistory_Call) Run(run func(trackerID uint, limit int)) *MockStatsService_GetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(int))
	})
	return _c
}

func (_c *MockStatsService_GetHistory_Call) Return(_a0 []domain.TrackerStats, _a1 error) *MockStatsService_GetHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsService_GetHistory_Call) RunAndReturn(run func(uint, int) ([]domain.TrackerStats, error)) *MockStatsService_GetHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobalHistory provides a mock function with given fields: limit
func (_m *MockStatsService) GetGlobalHistory(limit int) ([]domain.GlobalStatsPoint, error) {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalHistory")
	}

	var r0 []domain.GlobalStatsPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.GlobalStatsPoint, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.GlobalStatsPoint); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.GlobalStatsPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsService_GetGlobalHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalHistory'
type MockStatsService_GetGlobalHistory_Call struct {
	*mock.Call
}

// GetGlobalHistory is a helper method to define mock.On call
//   - limit int
func (_e *MockStatsService_Expecter) GetGlobalHistory(limit interface{}) *MockStatsService_GetGlobalHistory_Call {
	return &MockStatsService_GetGlobalHistory_Call{Call: _e.mock.On("GetGlobalHistory", limit)}
}

func (_c *MockStatsService_GetGlobalHistory_Call) Run(run func(limit int)) *MockStatsService_GetGlobalHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockStatsService_GetGlobalHistory_Call) Return(_a0 []domain.GlobalStatsPoint, _a1 error) *MockStatsService_GetGlobalHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsService_GetGlobalHistory_Call) RunAndReturn(run func(int) ([]domain.GlobalStatsPoint, error)) *MockStatsService_GetGlobalHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatest provides a mock function with given fields: trackerID
func (_m *MockStatsService) GetLatest(trackerID uint) (*domain.TrackerStats, error) {
	ret := _m.Called(trackerID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatest")
	}

	var r0 *domain.TrackerStats
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.TrackerStats, error)); ok {
		return rf(trackerID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.TrackerStats); ok {
		r0 = rf(trackerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TrackerStats)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(trackerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsService_GetLatest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatest'
type MockStatsService_GetLatest_Call struct {
	*mock.Call
}

// GetLatest is a helper method to define mock.On call
//   - trackerID uint
func (_e *MockStatsService_Expecter) GetLatest(trackerID interface{}) *MockStatsService_GetLatest_Call {
	return &MockStatsService_GetLatest_Call{Call: _e.mock.On("GetLatest", trackerID)}
}

func (_c *MockStatsService_GetLatest_Call) Run(run func(trackerID uint)) *MockStatsService_GetLatest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockStatsService_GetLatest_Call) Return(_a0 *domain.TrackerStats, _a1 error) *MockStatsService_GetLatest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsService_GetLatest_Call) RunAndReturn(run func(uint) (*domain.TrackerStats, error)) *MockStatsService_GetLatest_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistorySince provides a mock function with given fields: trackerID, since
func (_m *MockStatsService) GetHistorySince(trackerID uint, since time.Time) ([]domain.TrackerStats, error) {
	ret := _m.Called(trackerID, since)

	if len(ret) == 0 {
		panic("no return value specified for GetHistorySince")
	}

	var r0 []domain.TrackerStats
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, time.Time) ([]domain.TrackerStats, error)); ok {
		return rf(trackerID, since)
	}
	if rf, ok := ret.Get(0).(func(uint, time.Time) []domain.TrackerStats); ok {
		r0 = rf(trackerID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TrackerStats)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, time.Time) error); ok {
		r1 = rf(trackerID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsService_GetHistorySince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistorySince'
type MockStatsService_GetHistorySince_Call struct {
	*mock.Call
}

// GetHistorySince is a helper method to define mock.On call
//   - trackerID uint
//   - since time.Time
func (_e *MockStatsService_Expecter) GetHistorySince(trackerID interface{}, since interface{}) *MockStatsService_GetHistorySince_Call {
	return &MockStatsService_GetHistorySince_Call{Call: _e.mock.On("GetHistorySince", trackerID, since)}
}

func (_c *MockStatsService_GetHistorySince_Call) Run(run func(trackerID uint, since time.Time)) *MockStatsService_GetHistorySince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(time.Time))
	})
	return _c
}

func (_c *MockStatsService_GetHistorySince_Call) Return(_a0 []domain.TrackerStats, _a1 error) *MockStatsService_GetHistorySince_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsService_GetHistorySince_Call) RunAndReturn(run func(uint, time.Time) ([]domain.TrackerStats, error)) *MockStatsService_GetHistorySince_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatsService creates a new instance of MockStatsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatsService {
	mock := &MockStatsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
