// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/jose/ratiodash/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockMultisolverrConfigService is an autogenerated mock type for the MultisolverrConfigService type
type MockMultisolverrConfigService struct {
	mock.Mock
}

type MockMultisolverrConfigService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMultisolverrConfigService) EXPECT() *MockMultisolverrConfigService_Expecter {
	return &MockMultisolverrConfigService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with no fields
func (_m *MockMultisolverrConfigService) Get() (*domain.MultisolverrConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.MultisolverrConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() (*domain.MultisolverrConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *domain.MultisolverrConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MultisolverrConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMultisolverrConfigService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMultisolverrConfigService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockMultisolverrConfigService_Expecter) Get() *MockMultisolverrConfigService_Get_Call {
	return &MockMultisolverrConfigService_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockMultisolverrConfigService_Get_Call) Run(run func()) *MockMultisolverrConfigService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMultisolverrConfigService_Get_Call) Return(_a0 *domain.MultisolverrConfig, _a1 error) *MockMultisolverrConfigService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMultisolverrConfigService_Get_Call) RunAndReturn(run func() (*domain.MultisolverrConfig, error)) *MockMultisolverrConfigService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Test provides a mock function with given fields: baseURL
func (_m *MockMultisolverrConfigService) Test(baseURL string) error {
	ret := _m.Called(baseURL)

	if len(ret) == 0 {
		panic("no return value specified for Test")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(baseURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMultisolverrConfigService_Test_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Test'
type MockMultisolverrConfigService_Test_Call struct {
	*mock.Call
}

// Test is a helper method to define mock.On call
//   - baseURL string
func (_e *MockMultisolverrConfigService_Expecter) Test(baseURL interface{}) *MockMultisolverrConfigService_Test_Call {
	return &MockMultisolverrConfigService_Test_Call{Call: _e.mock.On("Test", baseURL)}
}

func (_c *MockMultisolverrConfigService_Test_Call) Run(run func(baseURL string)) *MockMultisolverrConfigService_Test_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMultisolverrConfigService_Test_Call) Return(_a0 error) *MockMultisolverrConfigService_Test_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMultisolverrConfigService_Test_Call) RunAndReturn(run func(string) error) *MockMultisolverrConfigService_Test_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: input
func (_m *MockMultisolverrConfigService) Update(input domain.UpdateMultisolverrConfigInput) (*domain.MultisolverrConfig, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.MultisolverrConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.UpdateMultisolverrConfigInput) (*domain.MultisolverrConfig, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(domain.UpdateMultisolverrConfigInput) *domain.MultisolverrConfig); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MultisolverrConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.UpdateMultisolverrConfigInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMultisolverrConfigService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMultisolverrConfigService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - input domain.UpdateMultisolverrConfigInput
func (_e *MockMultisolverrConfigService_Expecter) Update(input interface{}) *MockMultisolverrConfigService_Update_Call {
	return &MockMultisolverrConfigService_Update_Call{Call: _e.mock.On("Update", input)}
}

func (_c *MockMultisolverrConfigService_Update_Call) Run(run func(input domain.UpdateMultisolverrConfigInput)) *MockMultisolverrConfigService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.UpdateMultisolverrConfigInput))
	})
	return _c
}

func (_c *MockMultisolverrConfigService_Update_Call) Return(_a0 *domain.MultisolverrConfig, _a1 error) *MockMultisolverrConfigService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMultisolverrConfigService_Update_Call) RunAndReturn(run func(domain.UpdateMultisolverrConfigInput) (*domain.MultisolverrConfig, error)) *MockMultisolverrConfigService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMultisolverrConfigService creates a new instance of MockMultisolverrConfigService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMultisolverrConfigService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMultisolverrConfigService {
	mock := &MockMultisolverrConfigService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
